# This workflow will build a Java project with Maven
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-maven

name: Build and Test 5_testing Demo

on:
  push:
    branches: [ $default-branch ]
  pull_request:
    branches: [ $default-branch ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 15
      uses: actions/setup-java@v2
      with:
        java-version: '15'
        distribution: 'adopt'
    - name: Build parent POM
      run: mvn -B clean install --file 1_maven/demo/parent/pom.xml
    - name: Build and test 5_testing
      run: mvn -T1C -B clean verify --file 5_testing/demo/pom.xml

